apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: __APPBRANCH__
    name: __APPBRANCH__
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: __APPBRANCH__:latest
        namespace: __NAMESPACE__
      generation: 1
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/__APPBRANCH__
kind: List
